version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "backbook/node"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "frontbook/node"
    ports:
      - "3000:3000"
    links:
      - "backend:be"